#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/
# Modified for this use case

## $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook starting..."
# GITHUB_USERREPO="Herbaltea-GG/DSaaS"
# APPLICATION="DSaaS"

LATEST_TAG=$(git describe --tags --always)
SASS_RELEASE=$(curl -s https://api.github.com/repos/sass/dart-sass/tags | grep -A0 -m 1 '"name":' | awk '/name/{print substr($2,2,length($2)-3)}')


echo "[---] SASS_RELEASE: ${SASS_RELEASE}"
echo "[---] APPLICATION: ${APPLICATION}"

# Set description from github
DESCRIPTION=$(curl -s https://api.github.com/repos/${GITHUB_USERREPO} \
    | grep '"description".*' \
    | head -n 1 \
    | cut -d '"' -f 4)

echo "[---] GITHUB_USERREPO: ${GITHUB_USERREPO}"
echo "[---] LATEST_TAG: ${LATEST_TAG}"
echo "[---] DESCRIPTION: ${DESCRIPTION}"

# Build latest
docker build \
        --build-arg APPLICATION=${APPLICATION} \
        --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
        --build-arg REVISION=$(git rev-parse --short HEAD) \
    	--build-arg PACKAGE="${GITHUB_USERREPO}" \
        --build-arg DESCRIPTION="${DESCRIPTION}" \
        --build-arg VERSION="${LATEST_TAG}" \
        --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) \
        --build-arg RELEASE="${SASS_RELEASE}" \
        -t herbaltea/dsaas:latest \
        .

# Built most recent tag
docker build \
        --build-arg APPLICATION=${APPLICATION} \
        --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
        --build-arg REVISION=$(git rev-parse --short HEAD) \
    	--build-arg PACKAGE="${GITHUB_USERREPO}" \
        --build-arg DESCRIPTION="${DESCRIPTION}" \
        --build-arg VERSION="${LATEST_TAG}" \
        --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) \
        --build-arg RELEASE="${SASS_RELEASE}" \
        -t herbaltea/dsaas:$LATEST_TAG \
        .



echo "[***] Build hook completed."
